@startuml
skinparam classAttributeIconSize 0

class Evento{
date : Date
description : String
assign(l : Location) : void
}
class Conferencia{
max_attendees : Integer
}
class BoardMeeting{
}
Evento <|-- Conferencia
Evento <|-- BoardMeeting

class Persona{
name : String
}
class Member{
e-mail : String
}
class BoardMember{
}
Persona <|-- Member
Member<|-- BoardMember
class Localizacion{
description : String
address : String
}
class AAUOC{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}
AAUOC o-- Persona
AAUOC o-- Localizacion
AAUOC o-- Evento
Localizacion -- "isLocated In" Evento
Persona -- "attendsTo" Conferencia
Evento -- "attendsTo" Member
BoardMember -- "attendsTo" BoardMeeting

@enduml