@startuml
skinparam classAttributeIconSize 0

class Evento{
date : Date
description : String
assign(l : Location) : void
}
class Conferencia{
max_attendees : Integer
}
class BoardMeeting{
}
Evento <|-- Conferencia
Evento <|-- BoardMeeting

class Persona{
name : String
}
class Member{
e-mail : String
}
class BoardMember{
}
Persona <|-- Member
Member<|-- BoardMember
class Localizacion{
description : String
address : String
}
class AAUOC{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}
AAUOC o-- "0...*" Persona
AAUOC o-- "0...*" Localizacion
AAUOC o-- Evento
Localizacion "1"-- "0...*" Evento : "isLocated In"
Persona "0...*" -- "0...*"  Conferencia : "attendsTo"
Evento "0...*"-- "0...*" Member : "attendsTo"
BoardMember "0...*" -- "0...*" BoardMeeting :"attendsTo"
@enduml